/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117642-g08b1bffa49-20241025"
#endif /* AVUTIL_FFVERSION_H */
